### ISSUE TITLE
Does it run on Windows?

### ISSUE THREAD

**Issue by 11lucky111** [ogroth/tf-gqn#77]
I tried to run on a virtual machine, but it failed because there was no GPU.

**Comment by ogroth** [comment]
Hi lihao11, I've never tried to run the code on any other OS than Ubuntu. I can imagine that virtual machines have problems since they typically don't have native access to the GPU of the host system. You can try to add `os.environ['CUDA_VISIBLE_DEVICES'] = ''` to the script you execute. This will route the computations to CPU which will be painfully slow for training but you could at least ensure that the code runs. See the Jupyter notebook for view interpolation inference for an example: https://github.com/ogroth/tf-gqn/blob/master/notebooks/view_interpolation.ipynb
Hope that helps!
